rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/', views.add_page, name='add_page'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    # url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    )

twj_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'twj_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace='rango')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}),
    )

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name:")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.", initial="http://")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    # def clean(self):
    #     cleaned_data = self.cleaned_data
    #     url = cleaned_data.get('url')

    #     # If url is not empty and doesn't start with 'http://' add 'http://' to the beginning
    #     if url and not url.startswith('http://'):
    #         url = 'http://' + url

    #         cleaned_data['url'] = url
    #     return cleaned_data

    class Meta:
        model = Page
        exclude = ('category',)
        # fields = ('title', 'url', 'views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rango.bing_search import run_query


def index(request):

    category_list = Category.objects.order_by('-likes')[:5]
    category_list_most_viewed = Category.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'categories_most_viewed': category_list_most_viewed}

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).seconds > 0:
            visits = visits + 1
            reset_last_visit_time = True
    else:
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits

    context_dict['visits'] = visits

    response = render(request, 'rango/index.html', context_dict)

    return response
    # visits = int(request.COOKIES.get('visits', '0'))

    # reset_last_visit_time = False
    # #
    # context_dict['visits'] = visits
    # #
    # response = render(request, 'rango/index.html', context_dict)
    # if 'last_visit' in request.COOKIES:
    #   last_visit = request.COOKIES['last_visit']
    #   last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")
    #   if (datetime.now() - last_visit_time).days > 0:
    #       visits = visits + 1
    #       reset_last_visit_time = True
    # else:
    #   reset_last_visit_time = True
    #   context_dict['visits'] = visits
    #   response = render(request, 'rango/index.html', context_dict)

    # if reset_last_visit_time:
    #   response.set_cookie('last_visit', datetime.now())
    #   response.set_cookie('visits', visits)

    # return response
    # context_dict = {'boldmessage': 'I am bold font from the context'}
    # return render(request, 'rango/index.html', context_dict)
    # return HttpResponse("Rango says: Hello world! <br/> <a href='/rango/about'>About</a>")


def about(request):
    context_dict = {'desc': 'This is the about page in bold from the context'}

    if request.session.get('visits'):
        count = request.session.get('visits')
    else:
        count = 0
    context_dict['visits'] = count

    return render(request, 'rango/about.html', context_dict)
    # return HttpResponse("Rango says here is the about page <br/> <a href='/rango/'>Index</a>")


def category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name

        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages

        context_dict['category'] = category
        context_dict['cat'] = category_name_slug
    except Category.DoesNotExist:
        pass

    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print form.errors
    else:
        form = CategoryForm()

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):

    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()

                return category(request, category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()
    # DONE: changed category in context_dict to cat.slug
    context_dict = {'form': form, 'category': cat}

    return render(request, 'rango/add_page.html', context_dict)


def search(request):
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list})


@login_required
def restricted(request):
    # return HttpResponse("Since you're logged in, you can see this text!")
    return render(request, 'rango/restricted.html')


def track_url(request):
    if request.method  == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            page = Page.objects.get(id=page_id)
            page.views = page.views + 1
            page.save()
            return HttpResponseRedirect(page.url)
        # else:
        #     page = Page.objects.get(id=1)
        #     return HttpResponseRedirect(page.url)


# def register(request):
#   # A boolean value for telling the template whether the registration was successful.
#   # Set to False initially. Code changes value to True when registration succeeds.
#   registered = False

#   if request.method == 'POST':
#       user_form = UserForm(data=request.POST)
#       profile_form = UserProfileForm(data=request.POST)

#       if user_form.is_valid() and profile_form.is_valid():
#           user = user_form.save()
#           user.set_password(user.password)
#           user.save()

#           profile = profile_form.save(commit=False)
#           profile.user = user

#           if 'picture' in request.FILES:
#               profile.picture = request.FILES['picture']

#           profile.save()

#           registered = True

#       else:
#           print user_form.errors, profile_form.errors

#   else:
#       user_form = UserForm()
#       profile_form = UserProfileForm()

#   return render(request, 'rango/register.html',
#       {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


# def user_login(request):
#   if  request.method == 'POST':
#       username = request.POST['username']
#       password = request.POST['password']

#       user = authenticate(username=username, password=password)

#       if user:
#           if user.is_active:
#               login(request, user)
#               return HttpResponseRedirect('/rango/')
#           else:
#               return HttpResponse('Your Rango account is disabled.')

#       else:
#           print "Invalid login details: {0}, {1}".format(username, password)
#           return HttpResponse("Invalid login details supplied.")

#   else:
#       return render(request, 'rango/login.html', {})



# @login_required
# def user_logout(request):
#   logout(request)
#   return HttpResponseRedirect('/rango/')

templates/rango/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
        <h1>About</h1>
    </div>
    <div>
        <p>This is <strong>Rango's about page</strong></p>
        <p>You've visited this site on <strong>{{ visits }} occasion(s).</strong></p>
        <img  width="500" height="400" src="{% static "images/rango.jpg" %}" alt="Picture of Rango" /> <!-- New line -->
    </div>
    <a href="{% url 'rango:index' %}">Return to the Index Page</a><br />
{% endblock %}

<!-- <!DOCTYPE html>

{% load staticfiles %}

<html>
<head>
    <title>Rango: About</title>
</head>
<body>
    <h1>Rango says...</h1>
    About <strong>{{ desc }}</strong><br />
    <a href="/rango/">Index</a><br />

</body>
</html> -->

templates/rango/add_category.html
{% extends 'base.html' %}

{% block title %}Add Page{% endblock %}


{% block body_block %}

<div class="page-header">
    <h1>Add a Category</h1>
</div>

            <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
                    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}

    <input type="submit" name="submit" value="Create Category" />
</form>

{% endblock %}

templates/rango/add_page.html
{% extends 'base.html' %}

{% block title %}Add Page{% endblock %}


{% block body_block %}
{% if category %}

             <form role="form"  id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
            <h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}

                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br/>
                    {{ field }}<br/>
                {% endfor %}

             <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
             </form>
            {%  else %}
            <p>This is category does not exist.</p>
{%  endif %}


{% endblock %}

templates/rango/category.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <div class="page-header">
      <h1>{{ category_name }}</h1>
    </div
    {% if category %}
        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a><p> Views: {{ page.views }}</p></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
            <!-- <a href="/rango/category/{{ category.slug }}/add_page">Add a Page</a> -->
        {% endif %}
    {% else %}
        The specified Cateogry {{ category_name }} does not exist!
    {% endif %}
{% endblock %}

<!-- <!DOCTYPE html>
<html>
<head>
    <title>Rango</title>
</head>
<body>
    <h1>{{ category_name }}</h1>
    {% if category %}
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>No pages currently in category.</strong><br />
        {% endif %}

        {% if user.is_authenticated %}
        <a href="/rango/category/{{ cat }}/add_page/">Add Page</a><br />
        {% endif %}
    {% else %}
        The specified category {{ category_name }} does not exist!
    {% endif %}
</body>
</html> -->

templates/rango/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Index{% endblock %}

{% block body_block %}

{% if user.is_authenticated %}
    <div class="page-header">

                <h1>Rango says... Hello, {{ user.username }}!</h1>
            {% else %}
                <h1>Rango says... Hello World!</h1>
            {% endif %}
</div>

         <div class="row placeholders">
            <div class="col-xs-12 col-sm-6 placeholder">
               <div class="panel panel-primary">
    <div class="panel-heading">
            <h3 class="panel-title">Categories</h3>
    </div>
</div>

              {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                         <li class="list-group-item"><a href="{% url 'rango:category'  category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}

            </div>
            <div class="col-xs-12 col-sm-6 placeholder">
              <div class="panel panel-primary">
            <div class="panel-heading">
                    <h3 class="panel-title">Pages</h3>
            </div>
    </div>

                {% if pages %}
                    <ul class="list-group">
                        {% for page in pages %}
                         <li class="list-group-item"><a href="{{page.url}}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no pages present.</strong>
                {% endif %}
            </div>

          </div>


       <p> visits: {{ visits }}</p>
{% endblock %}